'use strict';

const express = require('express');
const http = require('http');
const path = require('path');
const { Server } = require('socket.io');
const RoomManager = require('./RoomManager');
const { EVENTS } = require('../../shared/constants');

// Level order is generated by scripts/export_level.py and shared with the
// client, so both sides agree on what comes next.
const { order: LEVEL_ORDER } = require('../../shared/levels.json');

const DEFAULT_LEVEL_ID = LEVEL_ORDER[0] || 'level_01';
const NEXT_LEVEL_DELAY = 4000; // matches the client's result overlay

/**
 * Loads a level's data so the room can track its objects. Falls back to the
 * bare id, which GameRoom accepts (no object tracking) if the file is gone.
 * @param {string} id
 * @returns {object|string}
 */
function loadLevel(id) {
  try {
    // Converted levels are served to the client from client/public/levels;
    // the hand-built one ships in the client bundle.
    if (id === 'level_01') return require('../../client/src/levels/level01.json');
    return require(`../../client/public/levels/${id}.json`);
  } catch (err) {
    console.warn(`[level] no data for ${id}: ${err.message}`);
    return id;
  }
}

/**
 * Move the whole room on to the next level once the result overlay has
 * had its moment.
 * @param {object} room
 */
function moveOn(room) {
  setTimeout(() => {
    if (!rooms.findRoom(room.code)) return; // room closed in the meantime
    if (room.battle) {
      const step = room.nextBattleStep();
      if (step.over) {
        io.to(room.code).emit(EVENTS.BATTLE_OVER, { winners: step.winners, points: step.points });
        room.state = 'lobby';
        console.log(`[battle_over] room=${room.code} winners=${step.winners.join(',')}`);
        return;
      }
      startLevel(room, step.level, step);
      return;
    }
    startLevel(room, nextLevelId(room.levelId));
  }, NEXT_LEVEL_DELAY);
}

/**
 * Start a level for the whole room.
 * @param {object} room
 * @param {string} levelId
 * @param {{hammer?: number, active?: string[]|null}} [step] a battle's
 */
function startLevel(room, levelId, step = {}) {
  room.startGame(loadLevel(levelId), step.active || null);
  const b = room.battle;
  io.to(room.code).emit(EVENTS.GAME_STARTED, {
    levelId,
    active: step.active || null,
    battle: b ? {
      set: b.set, level: b.index + 1, of: b.levels.length, tieBreak: b.tieBreak,
      hammer: step.hammer, points: { ...b.points },
    } : null,
  });
  console.log(`[start_level] room=${room.code} level=${levelId}`);
}

/**
 * @param {string} id
 * @returns {string} the level after `id`, wrapping around at the end
 */
function nextLevelId(id) {
  const i = LEVEL_ORDER.indexOf(id);
  return LEVEL_ORDER[(i + 1) % LEVEL_ORDER.length] || DEFAULT_LEVEL_ID;
}

const app = express();
const server = http.createServer(app);

// The client is served from this same server, so in production the browser
// talks same-origin and CORS never kicks in. CLIENT_URL only matters if the
// client is ever hosted elsewhere; without it, fall back to reflecting the
// request origin rather than to `undefined`, which silently blocks nothing
// but is easy to misread as a working allowlist.
const io = new Server(server, {
  cors: {
    origin: process.env.NODE_ENV === 'production'
      ? (process.env.CLIENT_URL || true)
      : '*',
    methods: ['GET', 'POST'],
  },
});

const PORT = process.env.PORT || 3000;
const rooms = new RoomManager();

// Serve client static files. The bundle's name carries its hash so it can
// be cached hard, but `index.html` points at that name and must never be:
// a stale copy asks for a bundle that no longer exists, and the page looks
// unchanged when it has in fact failed to load.
const clientDist = path.join(__dirname, '../../client/dist');
app.use(express.static(clientDist, {
  setHeaders: (res, filePath) => {
    if (filePath.endsWith('.html')) res.setHeader('Cache-Control', 'no-store');
  },
}));

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'ok' });
});

// Serve index.html for all non-API routes (SPA)
app.get('*', (req, res) => {
  if (!req.path.startsWith('/socket.io')) {
    res.sendFile(path.join(clientDist, 'index.html'));
  }
});

// Socket.io connection handling
io.on('connection', (socket) => {
  console.log(`[connect] socket=${socket.id}`);

  // --- create_room ---
  socket.on(EVENTS.CREATE_ROOM, ({ mode, playerName } = {}) => {
    if (!mode || !playerName) {
      socket.emit(EVENTS.JOIN_ERROR, { message: 'mode and playerName are required' });
      return;
    }

    const room = rooms.createRoom(mode, socket.id, playerName, io);
    const player = room.players.get(socket.id);

    socket.join(room.code);
    socket.emit(EVENTS.ROOM_CREATED, {
      code: room.code,
      playerId: socket.id,
      color: player.color,
    });

    console.log(`[create_room] code=${room.code} host=${socket.id} name=${playerName}`);
  });

  // --- join_room ---
  socket.on(EVENTS.JOIN_ROOM, ({ code, playerName } = {}) => {
    if (!code || !playerName) {
      socket.emit(EVENTS.JOIN_ERROR, { message: 'code and playerName are required' });
      return;
    }

    const room = rooms.findRoom(code.toUpperCase());
    if (!room) {
      socket.emit(EVENTS.JOIN_ERROR, { message: 'Room not found' });
      return;
    }

    const player = rooms.addPlayer(code.toUpperCase(), socket.id, playerName);
    if (player === false) {
      socket.emit(EVENTS.JOIN_ERROR, { message: 'Room is full' });
      return;
    }

    socket.join(room.code);

    // Send current state to the joining player
    socket.emit(EVENTS.ROOM_JOINED, {
      players: Array.from(room.players.values()),
      mode: room.mode,
      hostId: room.hostId,
    });

    // Notify everyone else in the room
    socket.to(room.code).emit(EVENTS.PLAYER_JOINED, { player });

    console.log(`[join_room] code=${room.code} socket=${socket.id} name=${playerName}`);
  });

  // --- player_ready ---
  socket.on(EVENTS.PLAYER_READY, () => {
    const room = rooms.getPlayerRoom(socket.id);
    if (!room) return;

    const player = room.players.get(socket.id);
    if (!player) return;

    player.ready = true;

    io.to(room.code).emit(EVENTS.PLAYER_READY_CHANGED, {
      playerId: socket.id,
      ready: true,
    });

    console.log(`[player_ready] socket=${socket.id} room=${room.code}`);
  });

  // --- start_game --- (host only)
  socket.on(EVENTS.START_GAME, (data = {}) => {
    const room = rooms.getPlayerRoom(socket.id);
    if (!room) return;
    if (socket.id !== room.hostId) return; // only host can start
    if (room.state === 'playing') return;

    // Use a minimal level descriptor; client sends full level data later
    // level_0A is converted straight from the original game's own files
    // (scripts/export_level.py); 'level_01' is the hand-built MVP level.
    room.onLevelEnd = () => moveOn(room);
    if (room.mode === 'battle') {
      // The host picks one of the original's five battle sets.
      const first = room.startBattle(data.set);
      startLevel(room, first.level, first);
    } else {
      room.battle = null;
      startLevel(room, DEFAULT_LEVEL_ID);
    }
    console.log(`[start_game] room=${room.code} host=${socket.id} mode=${room.mode}`);
  });

  // --- player_update ---
  socket.on(EVENTS.PLAYER_UPDATE, (data = {}) => {
    const room = rooms.getPlayerRoom(socket.id);
    if (!room) return;

    const { x, y, state, dir } = data;

    // Broadcast to everyone else in the room (not the sender)
    socket.to(room.code).emit(EVENTS.PLAYER_UPDATE, {
      playerId: socket.id,
      x,
      y,
      state,
      dir,
    });
  });

  // --- bell_hit ---
  socket.on(EVENTS.BELL_HIT, () => {
    const room = rooms.getPlayerRoom(socket.id);
    if (!room) return;
    const done = room.handleBellHit(socket.id);
    console.log(`[bell_hit] room=${room.code} socket=${socket.id} done=${done}`);
    if (done) moveOn(room);
  });

  // --- object_hit ---
  socket.on(EVENTS.OBJECT_HIT, (data = {}) => {
    const room = rooms.getPlayerRoom(socket.id);
    if (!room) return;
    room.handleObjectHit(socket.id, data.objectId, data.force);
    console.log(`[object_hit] room=${room.code} socket=${socket.id} objectId=${data.objectId}`);
  });

  // --- time_bonus ---
  socket.on(EVENTS.TIME_BONUS, (data = {}) => {
    const room = rooms.getPlayerRoom(socket.id);
    if (!room) return;
    room.addTime(data.seconds);
  });

  // --- disconnect ---
  socket.on('disconnect', () => {
    const room = rooms.getPlayerRoom(socket.id);
    if (room) {
      socket.to(room.code).emit(EVENTS.PLAYER_LEFT, { playerId: socket.id });
      console.log(`[player_left] socket=${socket.id} room=${room.code}`);
    }

    rooms.removePlayer(socket.id);
    // The bell may have been waiting for nobody but them.
    if (room && room.players.size > 0 && room.finishIfAllRang()) moveOn(room);
    console.log(`[disconnect] socket=${socket.id}`);
  });
});

server.listen(PORT, () => {
  console.log(`Server listening on port ${PORT}`);
});
