/**
 * Generated by scripts/export_level.py — do not edit by hand.
 * Levels converted straight from the original game's files.
 */
import level_0A from './level_0A.json';
import level_0B from './level_0B.json';
import level_0C from './level_0C.json';
import level_0D from './level_0D.json';
import level_0H from './level_0H.json';
import level_0J from './level_0J.json';
import level_0K from './level_0K.json';
import level_0S from './level_0S.json';
import level_1A from './level_1A.json';
import level_2H from './level_2H.json';
import level_3I from './level_3I.json';
import level_4A from './level_4A.json';

export const GENERATED_LEVELS = {
  level_0A,
  level_0B,
  level_0C,
  level_0D,
  level_0H,
  level_0J,
  level_0K,
  level_0S,
  level_1A,
  level_2H,
  level_3I,
  level_4A,
};
