"""
The symbol map of F.EXE, the front end: hand names (symbols.txt here)
plus the names a decompilation gives away, merged into one list for
Ghidra, and a measure of how much of the code has a name yet.

F.EXE is built like G.EXE (Watcom C, DOS/4GW LE, Miles Sound System
3.6B), but has none of the game's tables — no class registry, no object
templates — so the only derived names are the ones strings give away:

  - each Miles wrapper logs the call it makes, "AIL_<name>(…)";
  - the front end's debug output often names what a function is doing
    ("initialising main options screen", "doing init language select").

Usage (from the repository root):

    python3 scripts/ghidra/fexe/symbols.py table   > symbols.tsv   # for ApplySymbols.java
    python3 scripts/ghidra/fexe/symbols.py entries > entries.txt   # for MarkFunctions.java
    python3 scripts/ghidra/fexe/symbols.py coverage decomp.c       # what is named, what is next
    python3 scripts/ghidra/fexe/symbols.py strings decomp.c        # AIL names + string hints

The Java scripts are G.EXE's own (scripts/ghidra/*.java); they take any
address list and any table.
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))
sys.path.insert(0, os.path.join(REPO, "scripts", "formats"))

from disasm import Code   # noqa: E402

EXE = os.path.join(REPO, "Trash-it-original", "F.EXE")
HERE = os.path.dirname(os.path.abspath(__file__))
HAND = os.path.join(HERE, "symbols.txt")
#: Written by `symbols.py strings`: names a decompilation gives away.
FROM_STRINGS = os.path.join(HERE, "symbols_lib.txt")

#: The front end's own code is below this; above it, the linked libraries
#: (Miles Sound System, GrIP glue, the Watcom C runtime).
LIBRARY_LO = 0x55560

STRING_REF = re.compile(r"\b(?:s_|DAT_|PTR_s_)[A-Za-z0-9_]*?_?000([0-9a-f]{5})\b")


def load_hand(path=HAND):
    """symbols.txt -> {addr: (kind, name, comment)}"""
    out = {}
    if not os.path.exists(path):
        return out
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        body, _, comment = line.partition(";")
        addr, kind, name = body.split()[:3]
        out[int(addr, 16)] = (kind, name, comment.strip())
    return out


def merged():
    names = load_hand(FROM_STRINGS)
    names.update(load_hand())
    return names


def decomp_bodies(path):
    """decomp.c -> {addr: (name, body)}"""
    text = open(path, encoding="utf-8", errors="replace").read()
    parts = re.split(r"^// ==== (\S+) @ ([0-9a-f]+)\n", text, flags=re.M)
    return {int(parts[i + 1], 16): (parts[i], parts[i + 2])
            for i in range(1, len(parts) - 2, 3)}


def cmd_strings(code, decomp_path):
    """AIL wrappers by the call they log, and empty functions, into
    symbols_lib.txt; for the rest, the strings each function uses."""
    hand = load_hand()
    bodies = decomp_bodies(decomp_path)
    lines = ["# Generated by `fexe/symbols.py strings` from a decompilation: each",
             "# Miles wrapper logs the call it makes, \"AIL_<name>(…)\".",
             "# Do not edit; a name in symbols.txt wins over one here.", ""]
    hints = []
    seen = set()
    for addr, (name, body) in sorted(bodies.items()):
        texts = []
        for m in STRING_REF.finditer(body):
            t = code.cstring(int(m.group(1), 16))
            if t and t not in texts:
                texts.append(t)
        ail = [m.group(1) for t in texts for m in [re.match(r"(AIL_\w+)\(", t)] if m]
        if ail and addr >= LIBRARY_LO and addr not in hand and ail[0] not in seen:
            seen.add(ail[0])
            lines.append("0x%x  f  %s  ; logs \"%s(\"" % (addr, ail[0], ail[0]))
        elif texts and name.startswith("FUN_"):
            hints.append("0x%06x  %s" % (addr, " | ".join(repr(t)[1:-1] for t in texts[:4])))
    named = set(hand) | {int(l.split()[0], 16) for l in lines if l.startswith("0x")}
    lines += ["", "# Empty: a bare return — debug hooks compiled out."]
    for addr, (name, body) in sorted(bodies.items()):
        if addr not in named and re.fullmatch(
                r"\s*(/\*.*?\*/\s*)*\S[^{]*\{\s*return;\s*\}\s*", body, re.S):
            lines.append("0x%x  f  empty_%x  ; does nothing" % (addr, addr))
    with open(FROM_STRINGS, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print("%d generated names -> %s" % (sum(l.startswith("0x") for l in lines), FROM_STRINGS))
    print("\nunnamed functions and the strings they use:")
    print("\n".join(hints))


def cmd_table():
    for addr, (kind, name, comment) in sorted(merged().items()):
        print("%x\t%s\t%s\t%s" % (addr, kind, name, comment))


def cmd_entries(code):
    fs = {a for a, (k, _n, _c) in merged().items() if k == "f"}
    for a in sorted(set(code.entries()) | fs):
        print("%x" % a)


def cmd_coverage(code, decomp_path, top=40):
    bodies = decomp_bodies(decomp_path)
    names = merged()
    hand = load_hand()
    heads = {a: (names[a][1] if a in names and names[a][0] == "f" else n)
             for a, (n, _b) in bodies.items()}
    named = [a for a, n in heads.items() if not n.startswith("FUN_")]
    own = [a for a in heads if a < LIBRARY_LO]
    own_named = [a for a in named if a < LIBRARY_LO]
    print("functions in the dump:     %d (%d front end, %d library)"
          % (len(heads), len(own), len(heads) - len(own)))
    print("with a name:               %d (%.0f%%)" % (len(named), 100.0 * len(named) / max(1, len(heads))))
    print("  front end named:         %d of %d" % (len(own_named), len(own)))
    print("  of those, by hand:       %d" % sum(1 for a in named if a in hand))
    print("symbols: %d by hand, %d in total" % (len(hand), len(names)))
    calls = {}
    for _site, m, t in code._branches():
        if m == "call":
            calls[t] = calls.get(t, 0) + 1
    todo = sorted(((calls.get(a, 0), a) for a, n in heads.items()
                   if n.startswith("FUN_") and a < LIBRARY_LO), reverse=True)
    print("\nunnamed front-end functions, most called first:")
    for n, a in todo[:top]:
        print("  0x%06x  %4d calls  %5d lines" % (a, n, bodies[a][1].count("\n")))


def main(argv):
    cmd = argv[0] if argv else "table"
    if cmd == "table":
        cmd_table()
        return
    code = Code(EXE)
    if cmd == "entries":
        cmd_entries(code)
    elif cmd == "strings":
        cmd_strings(code, argv[1])
    elif cmd == "coverage":
        cmd_coverage(code, argv[1], int(argv[2]) if len(argv) > 2 else 40)
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main(sys.argv[1:])
